### ISSUE TITLE
Some lines will not be displayed

### ISSUE THREAD

**Issue by yyy33** [amarakon/nvim-cmp-buffer-lines#2]
Please see, The first line of the first document is not shown in the complementary menu and the third line of the second document is not shown in the complementary menu

![gg](https://user-images.githubusercontent.com/51548147/201556878-6d9a28d4-2948-4779-8e0a-874acda853bc.png)
![zzz](https://user-images.githubusercontent.com/51548147/201557488-c4551de3-61b9-4720-b0d7-705c6e7f71d6.png)

mini config
```
local buffer_lines = {
    name = "buffer-lines",
    option = {
        comments = true,
    },
}
local global_source = {
    buffer_lines,
}
cmp.setup({
    sources = global_source,
})

```

document
```
    if ₁ = ₂ then
end
        abcdefg


```

```
end
        abcdefg

[system="Linux" class="Alacritty" modifier="(MetaLeft ShiftLeft)"]


```

**Comment by amarz45** [comment]
The reason those lines will not be displayed is because you are already on the line. By default, nvim-cmp-buffer-lines does not show a line if you are already on that line. This is to prevent you from seeing the current line as a result as you're writing it in insert mode. Would you like me to make it so that this only happens in insert mode so that the current line shows in command mode?

**Comment by yyy33** [comment]
> The reason those lines will not be displayed is because you are already on the line. By default, nvim-cmp-buffer-lines does not show a line if you are already on that line. This is to prevent you from seeing the current line as a result as you're writing it in insert mode. Would you like me to make it so that this only happens in insert mode so that the current line shows in command mode?

Your default settings are reasonable, I was a little confused here and thought it was a bug，thank you
